//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_B8PRkQqlEe-zQquRjvk7fwActivity"]="./../../Analysis_Design/capabilitypatterns/resources/Define a Candidate Architecture_9286F9AB_9286f9ab_Activity.jpeg"
contentPage.processPage.imageFiles["_B8PRkQqlEe-zQquRjvk7fwActivityDetail"]="./../../Analysis_Design/capabilitypatterns/resources/Define a Candidate Architecture_9286F9AB_9286f9ab_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_ymDFEQswEe-PSemMSezamgActivity"]="./../../Analysis_Design/capabilitypatterns/resources/Perform Architectural Synthesis_1F6C356D_1f6c356d_Activity.jpeg"
contentPage.processPage.imageFiles["_ymDFEQswEe-PSemMSezamgActivityDetail"]="./../../Analysis_Design/capabilitypatterns/resources/Perform Architectural Synthesis_1F6C356D_1f6c356d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_vxRI8QszEe-PSemMSezamgActivity"]="./../../Analysis_Design/capabilitypatterns/resources/Analyze Behavior_3C7033C0_3c7033c0_Activity.jpeg"
contentPage.processPage.imageFiles["_vxRI8QszEe-PSemMSezamgActivityDetail"]="./../../Analysis_Design/capabilitypatterns/resources/Analyze Behavior_3C7033C0_3c7033c0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_NOpM8Qs0Ee-PSemMSezamgActivity"]="./../../Analysis_Design/capabilitypatterns/resources/Refine the Architecture_953FA89B_953fa89b_Activity.jpeg"
contentPage.processPage.imageFiles["_NOpM8Qs0Ee-PSemMSezamgActivityDetail"]="./../../Analysis_Design/capabilitypatterns/resources/Refine the Architecture_953FA89B_953fa89b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_muIfEQs0Ee-PSemMSezamgActivity"]="./../../Analysis_Design/capabilitypatterns/resources/Design Components_858A11F5_858a11f5_Activity.jpeg"
contentPage.processPage.imageFiles["_muIfEQs0Ee-PSemMSezamgActivityDetail"]="./../../Analysis_Design/capabilitypatterns/resources/Design Components_858A11F5_858a11f5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0Sk7gQs0Ee-PSemMSezamgActivity"]="./../../Analysis_Design/capabilitypatterns/resources/Design the Database_E7F28D3D_e7f28d3d_Activity.jpeg"
contentPage.processPage.imageFiles["_0Sk7gQs0Ee-PSemMSezamgActivityDetail"]="./../../Analysis_Design/capabilitypatterns/resources/Design the Database_E7F28D3D_e7f28d3d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_Ql_4gQwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Define a Candidate Architecture_3C649D4_b218dbaa_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_Ql_4gQwfEe-e9-FHsoqqEgActivityDetail"]="./../../Analysis_Design/deliveryprocesses/resources/Define a Candidate Architecture_3C649D4_b218dbaa_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_RDzO0QwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Design Components_7617FF02_246a90d8_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_RDzO0QwfEe-e9-FHsoqqEgActivityDetail"]="./../../Analysis_Design/deliveryprocesses/resources/Design Components_7617FF02_246a90d8_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_RduKsQwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Design the Database_BE922660_6ce4b836_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_RduKsQwfEe-e9-FHsoqqEgActivityDetail"]="./../../Analysis_Design/deliveryprocesses/resources/Design the Database_BE922660_6ce4b836_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Analysis Design process_4A71E982_4a71e982_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_QCs-MAwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Analyze Behavior_76D4341A_2526c5f0_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_QCs-MAwfEe-e9-FHsoqqEgActivityDetail"]="./../../Analysis_Design/deliveryprocesses/resources/Analyze Behavior_76D4341A_2526c5f0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_R5-B0QwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Perform Architectural Synthesis_9BCD2B13_4a1fbce9_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_R5-B0QwfEe-e9-FHsoqqEgActivityDetail"]="./../../Analysis_Design/deliveryprocesses/resources/Perform Architectural Synthesis_9BCD2B13_4a1fbce9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_STBbAQwfEe-e9-FHsoqqEgActivity"]="./../../Analysis_Design/deliveryprocesses/resources/Refine the Architecture_6C1B724B_1a6e0421_Activity.jpeg"
contentPage.processPage.imageFiles["_M3e_YAwfEe-e9-FHsoqqEg,_STBbAQwfEe-e9-FHsoqqEgActivityDetail"]="./../../Analysis_Design/deliveryprocesses/resources/Refine the Architecture_6C1B724B_1a6e0421_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_ymDFEQswEe-PSemMSezamg"] = ["Perform Architectural Synthesis","Analysis_Design/capabilitypatterns/Perform Architectural Synthesis_1F6C356D.html"];
contentPage.processPage.elementUrls["_twOo0gs0Ee-PSemMSezamg"] = ["Diseñador","Analysis_Design/roles/Designer_864373B1.html"];
contentPage.processPage.elementUrls["_WJDjNAs0Ee-PSemMSezamg"] = ["Incorporate Existing Design Elements","Analysis_Design/tasks/Incorporate Existing Design Elements_F0CC3A24.html"];
contentPage.processPage.elementUrls["_WJExUgs0Ee-PSemMSezamg"] = ["Event","Analysis_Design/workproducts/Event_1E53D346.html"];
contentPage.processPage.elementUrls["_twOBwgs0Ee-PSemMSezamg"] = ["Design Test Classes and Packages","Analysis_Design/tasks/Design Test Classes and Packages_71E84721.html"];
contentPage.processPage.elementUrls["_WJEKQgs0Ee-PSemMSezamg"] = ["Implementation Model","Analysis_Design/workproducts/Implementation Model_A81C68ED.html"];
contentPage.processPage.elementUrls["_TuEkFAwcEe-e9-FHsoqqEg"] = ["Use-Case Modeling Guidelines","Analysis_Design/workproducts/Use-Case Modeling Guidelines_70473D0D.html"];
contentPage.processPage.elementUrls["_5h6uMgs0Ee-PSemMSezamg"] = ["Diseño de modelo","Analysis_Design/workproducts/Design_model_6B2A6C03.html"];
contentPage.processPage.elementUrls["_WJEKUgs0Ee-PSemMSezamg"] = ["Design Package","Analysis_Design/workproducts/Design Package_23B609B4.html"];
contentPage.processPage.elementUrls["_0Sk7gQs0Ee-PSemMSezamg"] = ["Design the Database","Analysis_Design/capabilitypatterns/Design the Database_E7F28D3D.html"];
contentPage.processPage.elementUrls["_HfL3IAsxEe-PSemMSezamg"] = ["Arquitecto de Software","Analysis_Design/roles/Software Architect_E170FB33.html"];
contentPage.processPage.elementUrls["_m2RUYgqlEe-zQquRjvk7fw"] = ["Documento de Arquitectura de software","Analysis_Design/workproducts/Software_Architecture_Document_680C215E.html"];
contentPage.processPage.elementUrls["_HfOTYAsxEe-PSemMSezamg"] = ["Vision","Analysis_Design/workproducts/Vision_D385BFBC.html"];
contentPage.processPage.elementUrls["_twOBxAs0Ee-PSemMSezamg"] = ["Subsystem Design","Analysis_Design/tasks/Subsystem Design_17054A4D.html"];
contentPage.processPage.elementUrls["_R5-B0QwfEe-e9-FHsoqqEg"] = ["Perform Architectural Synthesis","Analysis_Design/deliveryprocesses/Perform Architectural Synthesis_9BCD2B13.html"];
contentPage.processPage.elementUrls["_4TTbcgszEe-PSemMSezamg"] = ["Change Request","Analysis_Design/workproducts/change_request_A7B19A71.html"];
contentPage.processPage.elementUrls["_WJDjMQs0Ee-PSemMSezamg"] = ["Describe the Run-time Architecture","Analysis_Design/tasks/Describe the Run-time Architecture_D8B706E7.html"];
contentPage.processPage.elementUrls["_m2QtVAqlEe-zQquRjvk7fw"] = ["Diseño de Guidelines","Analysis_Design/workproducts/Design_guidelines_2FDE899D.html"];
contentPage.processPage.elementUrls["_5h7VRAs0Ee-PSemMSezamg"] = ["Design Class","Analysis_Design/workproducts/Design Class_3C0E8D44.html"];
contentPage.processPage.elementUrls["_m2QtVgqlEe-zQquRjvk7fw"] = ["Diseño de modelo","Analysis_Design/workproducts/Design_model_6B2A6C03.html"];
contentPage.processPage.elementUrls["_twP28ws0Ee-PSemMSezamg"] = ["Interface","Analysis_Design/workproducts/Interface_63DAC3B0.html"];
contentPage.processPage.elementUrls["_HfNsVwsxEe-PSemMSezamg"] = ["Architectural Proof-of-Concept","Analysis_Design/workproducts/Architectural Proof-of-Concept_8C42E6C6.html"];
contentPage.processPage.elementUrls["_4TS0YAszEe-PSemMSezamg"] = ["Review the Design","Analysis_Design/tasks/review_the_design_61436785.html"];
contentPage.processPage.elementUrls["_twOo2gs0Ee-PSemMSezamg"] = ["Protocol","Analysis_Design/workproducts/Protocol_162F669D.html"];
contentPage.processPage.elementUrls["_5h5gEAs0Ee-PSemMSezamg"] = ["Database Design","Analysis_Design/tasks/database_design_BE98972F.html"];
contentPage.processPage.elementUrls["_HfNsUwsxEe-PSemMSezamg"] = ["Modelo desplegado","Analysis_Design/workproducts/Deployment_Model_717C1197.html"];
contentPage.processPage.elementUrls["_TuFLIQwcEe-e9-FHsoqqEg"] = ["Analysis Model","Analysis_Design/workproducts/Analysis Model_A4C2857A.html"];
contentPage.processPage.elementUrls["_WJExUAs0Ee-PSemMSezamg"] = ["Design Subsystem","Analysis_Design/workproducts/Design Subsystem_1C536B3.html"];
contentPage.processPage.elementUrls["_twOo1As0Ee-PSemMSezamg"] = ["Design Reviewer","Analysis_Design/roles/design_reviewer_571629E1.html"];
contentPage.processPage.elementUrls["_m2RUagqlEe-zQquRjvk7fw"] = ["Realización de casos de uso","Analysis_Design/workproducts/Use-Case_Realization_CCB217D6.html"];
contentPage.processPage.elementUrls["_HfNsUQsxEe-PSemMSezamg"] = ["Modelo de caso de uso","Analysis_Design/workproducts/Use-Case_Model_1F2B9540.html"];
contentPage.processPage.elementUrls["_WJEKTgs0Ee-PSemMSezamg"] = ["Diseño de Guidelines","Analysis_Design/workproducts/Design_guidelines_2FDE899D.html"];
contentPage.processPage.elementUrls["_twPP7As0Ee-PSemMSezamg"] = ["Design Package","Analysis_Design/workproducts/Design Package_23B609B4.html"];
contentPage.processPage.elementUrls["_5h45AAs0Ee-PSemMSezamg"] = ["Class Design","Analysis_Design/tasks/Class Design_BC9AFEFF.html"];
contentPage.processPage.elementUrls["_twOo1gs0Ee-PSemMSezamg"] = ["Capsule","Analysis_Design/workproducts/Capsule_23FD9C24.html"];
contentPage.processPage.elementUrls["_twPP4gs0Ee-PSemMSezamg"] = ["Design Class","Analysis_Design/workproducts/Design Class_3C0E8D44.html"];
contentPage.processPage.elementUrls["_twPP9As0Ee-PSemMSezamg"] = ["Change Request","Analysis_Design/workproducts/change_request_A7B19A71.html"];
contentPage.processPage.elementUrls["_HfNFSAsxEe-PSemMSezamg"] = ["Especificaciones suplementarias","Analysis_Design/workproducts/Supplementary_Specifications_C7445C8B.html"];
contentPage.processPage.elementUrls["_2ybemAszEe-PSemMSezamg"] = ["Boundary Class","Analysis_Design/workproducts/Boundary Class_B23D893D.html"];
contentPage.processPage.elementUrls["_HfNsWwsxEe-PSemMSezamg"] = ["Business Case","Analysis_Design/workproducts/Business Case_4A99B009.html"];
contentPage.processPage.elementUrls["_twPP4As0Ee-PSemMSezamg"] = ["Signal","Analysis_Design/workproducts/Signal_DAA12F00.html"];
contentPage.processPage.elementUrls["_m2QGQAqlEe-zQquRjvk7fw"] = ["Análisis de casos de uso","Analysis_Design/tasks/Use-Case_Analysis_E9DFF682.html"];
contentPage.processPage.elementUrls["_2ybelAszEe-PSemMSezamg"] = ["Modelo de caso de uso","Analysis_Design/workproducts/Use-Case_Model_1F2B9540.html"];
contentPage.processPage.elementUrls["_twOBwAs0Ee-PSemMSezamg"] = ["Capsule Design","Analysis_Design/tasks/Capsule Design_A2DC2DF3.html"];
contentPage.processPage.elementUrls["_2ybelgszEe-PSemMSezamg"] = ["Realización de casos de uso","Analysis_Design/workproducts/Use-Case_Realization_CCB217D6.html"];
contentPage.processPage.elementUrls["_XpYtgQs0Ee-PSemMSezamg"] = ["Risk List","Analysis_Design/workproducts/Risk List_400273A4.html"];
contentPage.processPage.elementUrls["_2ya3gAszEe-PSemMSezamg"] = ["Documento de Arquitectura de software","Analysis_Design/workproducts/Software_Architecture_Document_680C215E.html"];
contentPage.processPage.elementUrls["_2ya3jgszEe-PSemMSezamg"] = ["Interface","Analysis_Design/workproducts/Interface_63DAC3B0.html"];
contentPage.processPage.elementUrls["_5h7VRgs0Ee-PSemMSezamg"] = ["Data model","Analysis_Design/workproducts/Data model_2181E19B.html"];
contentPage.processPage.elementUrls["_HfNFQgsxEe-PSemMSezamg"] = ["Diseño de modelo","Analysis_Design/workproducts/Design_model_6B2A6C03.html"];
contentPage.processPage.elementUrls["_2ya3igszEe-PSemMSezamg"] = ["Design Subsystem","Analysis_Design/workproducts/Design Subsystem_1C536B3.html"];
contentPage.processPage.elementUrls["_m2RUaAqlEe-zQquRjvk7fw"] = ["Modelo desplegado","Analysis_Design/workproducts/Deployment_Model_717C1197.html"];
contentPage.processPage.elementUrls["_2yaQdAszEe-PSemMSezamg"] = ["Análisis de clases","Analysis_Design/workproducts/Analysis_Class_840B7D59.html"];
contentPage.processPage.elementUrls["_RduKsQwfEe-e9-FHsoqqEg"] = ["Design the Database","Analysis_Design/deliveryprocesses/Design the Database_BE922660.html"];
contentPage.processPage.elementUrls["_WJEKRgs0Ee-PSemMSezamg"] = ["Capsule","Analysis_Design/workproducts/Capsule_23FD9C24.html"];
contentPage.processPage.elementUrls["_XpYGcQs0Ee-PSemMSezamg"] = ["Architecture Reviewer","Analysis_Design/roles/Architecture Reviewer_1E732B95.html"];
contentPage.processPage.elementUrls["_twOBwQs0Ee-PSemMSezamg"] = ["Class Design","Analysis_Design/tasks/Class Design_BC9AFEFF.html"];
contentPage.processPage.elementUrls["_twOBxQs0Ee-PSemMSezamg"] = ["Use-Case Design","Analysis_Design/tasks/Use-Case Design_9F7118E2.html"];
contentPage.processPage.elementUrls["_5h7VQAs0Ee-PSemMSezamg"] = ["Especificaciones suplementarias","Analysis_Design/workproducts/Supplementary_Specifications_C7445C8B.html"];
contentPage.processPage.elementUrls["_WJEKQAs0Ee-PSemMSezamg"] = ["Modelo desplegado","Analysis_Design/workproducts/Deployment_Model_717C1197.html"];
contentPage.processPage.elementUrls["_2yZpYAszEe-PSemMSezamg"] = ["Identify Design Elements","Analysis_Design/tasks/Identify Design Elements_890E5AE0.html"];
contentPage.processPage.elementUrls["_m2RUZAqlEe-zQquRjvk7fw"] = ["Especificaciones suplementarias","Analysis_Design/workproducts/Supplementary_Specifications_C7445C8B.html"];
contentPage.processPage.elementUrls["_twOo0As0Ee-PSemMSezamg"] = ["Capsule Designer","Analysis_Design/roles/Capsule Designer_5F467EDC.html"];
contentPage.processPage.elementUrls["_WJDjMAs0Ee-PSemMSezamg"] = ["Describe Distribution","Analysis_Design/tasks/Describe Distribution_D4D6417.html"];
contentPage.processPage.elementUrls["_WJEKRAs0Ee-PSemMSezamg"] = ["Documento de Arquitectura de software","Analysis_Design/workproducts/Software_Architecture_Document_680C215E.html"];
contentPage.processPage.elementUrls["_5h6uMAs0Ee-PSemMSezamg"] = ["Diseño de Guidelines","Analysis_Design/workproducts/Design_guidelines_2FDE899D.html"];
contentPage.processPage.elementUrls["_5h5gEQs0Ee-PSemMSezamg"] = ["Review the Design","Analysis_Design/tasks/review_the_design_61436785.html"];
contentPage.processPage.elementUrls["_5h6HJAs0Ee-PSemMSezamg"] = ["Design Reviewer","Analysis_Design/roles/design_reviewer_571629E1.html"];
contentPage.processPage.elementUrls["_m2QGQQqlEe-zQquRjvk7fw"] = ["Arquitecto de Software","Analysis_Design/roles/Software Architect_E170FB33.html"];
contentPage.processPage.elementUrls["_2ybengszEe-PSemMSezamg"] = ["Analysis Model","Analysis_Design/workproducts/Analysis Model_A4C2857A.html"];
contentPage.processPage.elementUrls["_5h6HIAs0Ee-PSemMSezamg"] = ["Diseñador","Analysis_Design/roles/Designer_864373B1.html"];
contentPage.processPage.elementUrls["_B8PRkQqlEe-zQquRjvk7fw"] = ["Definir arquitectura candidata","Analysis_Design/capabilitypatterns/Define a Candidate Architecture_9286F9AB.html"];
contentPage.processPage.elementUrls["_m2RUbAqlEe-zQquRjvk7fw"] = ["Análisis de clases","Analysis_Design/workproducts/Analysis_Class_840B7D59.html"];
contentPage.processPage.elementUrls["_HfMeMAsxEe-PSemMSezamg"] = ["Glosario","Analysis_Design/workproducts/Glosary_E2625D8.html"];
contentPage.processPage.elementUrls["_4TTbcAszEe-PSemMSezamg"] = ["Design Reviewer","Analysis_Design/roles/design_reviewer_571629E1.html"];
contentPage.processPage.elementUrls["_HfLQEQsxEe-PSemMSezamg"] = ["Construct Architectural Proof-of-Concept","Analysis_Design/tasks/Construct Architectural Proof-of-Concept_E9C1FE29.html"];
contentPage.processPage.elementUrls["_HfLQEAsxEe-PSemMSezamg"] = ["Assess Viability of Architectural Proof-of-Concept","Analysis_Design/tasks/Assess Viability of Architectural Proof-of-Concept_EF6C76BC.html"];
contentPage.processPage.elementUrls["_5h6uNgs0Ee-PSemMSezamg"] = ["Signal","Analysis_Design/workproducts/Signal_DAA12F00.html"];
contentPage.processPage.elementUrls["_XpYGcAs0Ee-PSemMSezamg"] = ["Review the Architecture","Analysis_Design/tasks/review_the_architecture_3A1FE81C.html"];
contentPage.processPage.elementUrls["_WJExVgs0Ee-PSemMSezamg"] = ["Protocol","Analysis_Design/workproducts/Protocol_162F669D.html"];
contentPage.processPage.elementUrls["_XpYthQs0Ee-PSemMSezamg"] = ["Review Record","Analysis_Design/workproducts/review_record_E296D06A.html"];
contentPage.processPage.elementUrls["_HfNsWQsxEe-PSemMSezamg"] = ["Risk List","Analysis_Design/workproducts/Risk List_400273A4.html"];
contentPage.processPage.elementUrls["_twPP6gs0Ee-PSemMSezamg"] = ["Realización de casos de uso","Analysis_Design/workproducts/Use-Case_Realization_CCB217D6.html"];
contentPage.processPage.elementUrls["_2ybekgszEe-PSemMSezamg"] = ["Glosario","Analysis_Design/workproducts/Glosary_E2625D8.html"];
contentPage.processPage.elementUrls["_2yaQcgszEe-PSemMSezamg"] = ["Diseñador","Analysis_Design/roles/Designer_864373B1.html"];
contentPage.processPage.elementUrls["_twPP5gs0Ee-PSemMSezamg"] = ["Diseño de modelo","Analysis_Design/workproducts/Design_model_6B2A6C03.html"];
contentPage.processPage.elementUrls["_2yZpYQszEe-PSemMSezamg"] = ["Análisis de casos de uso","Analysis_Design/tasks/Use-Case_Analysis_E9DFF682.html"];
contentPage.processPage.elementUrls["_2ya3iAszEe-PSemMSezamg"] = ["Design Package","Analysis_Design/workproducts/Design Package_23B609B4.html"];
contentPage.processPage.elementUrls["_2ybemgszEe-PSemMSezamg"] = ["Use Case","Analysis_Design/workproducts/Use Case_C0CAA954.html"];
contentPage.processPage.elementUrls["_NOpM8Qs0Ee-PSemMSezamg"] = ["Refine the Architecture","Analysis_Design/capabilitypatterns/Refine the Architecture_953FA89B.html"];
contentPage.processPage.elementUrls["_4TTbdAszEe-PSemMSezamg"] = ["Review Record","Analysis_Design/workproducts/review_record_E296D06A.html"];
contentPage.processPage.elementUrls["_muIfEQs0Ee-PSemMSezamg"] = ["Design Components","Analysis_Design/capabilitypatterns/Design Components_858A11F5.html"];
contentPage.processPage.elementUrls["_twP29Qs0Ee-PSemMSezamg"] = ["Use Case","Analysis_Design/workproducts/Use Case_C0CAA954.html"];
contentPage.processPage.elementUrls["_m2RUYAqlEe-zQquRjvk7fw"] = ["Referencia de Arquitectura","Analysis_Design/workproducts/Reference_Architecture_8D6B30F3.html"];
contentPage.processPage.elementUrls["_HfNFRAsxEe-PSemMSezamg"] = ["Referencia de Arquitectura","Analysis_Design/workproducts/Reference_Architecture_8D6B30F3.html"];
contentPage.processPage.elementUrls["_2ya3hAszEe-PSemMSezamg"] = ["Capsule","Analysis_Design/workproducts/Capsule_23FD9C24.html"];
contentPage.processPage.elementUrls["_WJEKUAs0Ee-PSemMSezamg"] = ["Design Class","Analysis_Design/workproducts/Design Class_3C0E8D44.html"];
contentPage.processPage.elementUrls["_TuEkEQwcEe-e9-FHsoqqEg"] = ["Use Case","Analysis_Design/workproducts/Use Case_C0CAA954.html"];
contentPage.processPage.elementUrls["_m2QtUgqlEe-zQquRjvk7fw"] = ["Glosario","Analysis_Design/workproducts/Glosary_E2625D8.html"];
contentPage.processPage.elementUrls["_twP28Qs0Ee-PSemMSezamg"] = ["Design Subsystem","Analysis_Design/workproducts/Design Subsystem_1C536B3.html"];
contentPage.processPage.elementUrls["_twPP9gs0Ee-PSemMSezamg"] = ["Review Record","Analysis_Design/workproducts/review_record_E296D06A.html"];
contentPage.processPage.elementUrls["_RDzO0QwfEe-e9-FHsoqqEg"] = ["Design Components","Analysis_Design/deliveryprocesses/Design Components_7617FF02.html"];
contentPage.processPage.elementUrls["_2ya3ggszEe-PSemMSezamg"] = ["Especificaciones suplementarias","Analysis_Design/workproducts/Supplementary_Specifications_C7445C8B.html"];
contentPage.processPage.elementUrls["_2yaQeAszEe-PSemMSezamg"] = ["Diseño de modelo","Analysis_Design/workproducts/Design_model_6B2A6C03.html"];
contentPage.processPage.elementUrls["_5h7VSAs0Ee-PSemMSezamg"] = ["Change Request","Analysis_Design/workproducts/change_request_A7B19A71.html"];
contentPage.processPage.elementUrls["_5h7VSgs0Ee-PSemMSezamg"] = ["Review Record","Analysis_Design/workproducts/review_record_E296D06A.html"];
contentPage.processPage.elementUrls["_twPP7gs0Ee-PSemMSezamg"] = ["Test Case","Analysis_Design/workproducts/test_case_D9D0C2F0.html"];
contentPage.processPage.elementUrls["_2ybenAszEe-PSemMSezamg"] = ["Use-Case Modeling Guidelines","Analysis_Design/workproducts/Use-Case Modeling Guidelines_70473D0D.html"];
contentPage.processPage.elementUrls["_2ya3hgszEe-PSemMSezamg"] = ["Design Class","Analysis_Design/workproducts/Design Class_3C0E8D44.html"];
contentPage.processPage.elementUrls["_vxRI8QszEe-PSemMSezamg"] = ["Analyze Behavior","Analysis_Design/capabilitypatterns/Analyze Behavior_3C7033C0.html"];
contentPage.processPage.elementUrls["_2yaQcAszEe-PSemMSezamg"] = ["Arquitecto de Software","Analysis_Design/roles/Software Architect_E170FB33.html"];
contentPage.processPage.elementUrls["_twPP5As0Ee-PSemMSezamg"] = ["Diseño de Guidelines","Analysis_Design/workproducts/Design_guidelines_2FDE899D.html"];
contentPage.processPage.elementUrls["_twPP8As0Ee-PSemMSezamg"] = ["Test Class","Analysis_Design/workproducts/test_class_B6DCBB45.html"];
contentPage.processPage.elementUrls["_WJEKSAs0Ee-PSemMSezamg"] = ["Diseño de modelo","Analysis_Design/workproducts/Design_model_6B2A6C03.html"];
contentPage.processPage.elementUrls["_5h7VQgs0Ee-PSemMSezamg"] = ["Realización de casos de uso","Analysis_Design/workproducts/Use-Case_Realization_CCB217D6.html"];
contentPage.processPage.elementUrls["_HfOTYgsxEe-PSemMSezamg"] = ["User-Interface Prototype","Analysis_Design/workproducts/User-Interface Prototype_9B84599E.html"];
contentPage.processPage.elementUrls["_STBbAQwfEe-e9-FHsoqqEg"] = ["Refine the Architecture","Analysis_Design/deliveryprocesses/Refine the Architecture_6C1B724B.html"];
contentPage.processPage.elementUrls["_TuD9AQwcEe-e9-FHsoqqEg"] = ["Boundary Class","Analysis_Design/workproducts/Boundary Class_B23D893D.html"];
contentPage.processPage.elementUrls["_twPP8gs0Ee-PSemMSezamg"] = ["Test Interface Specification","Analysis_Design/workproducts/test_interface_specification_EC653C42.html"];
contentPage.processPage.elementUrls["_m2QtUAqlEe-zQquRjvk7fw"] = ["Diseñador","Analysis_Design/roles/Designer_864373B1.html"];
contentPage.processPage.elementUrls["_HfNFRgsxEe-PSemMSezamg"] = ["Documento de Arquitectura de software","Analysis_Design/workproducts/Software_Architecture_Document_680C215E.html"];
contentPage.processPage.elementUrls["_WJExVAs0Ee-PSemMSezamg"] = ["Interface","Analysis_Design/workproducts/Interface_63DAC3B0.html"];
contentPage.processPage.elementUrls["_m2PfMAqlEe-zQquRjvk7fw"] = ["Análisis_arquitectónico","Analysis_Design/tasks/Architectural Analysis_BA0A4B6.html"];
contentPage.processPage.elementUrls["_WJEKSgs0Ee-PSemMSezamg"] = ["Especificaciones suplementarias","Analysis_Design/workproducts/Supplementary_Specifications_C7445C8B.html"];
contentPage.processPage.elementUrls["_twOo2As0Ee-PSemMSezamg"] = ["Event","Analysis_Design/workproducts/Event_1E53D346.html"];
contentPage.processPage.elementUrls["_QCs-MAwfEe-e9-FHsoqqEg"] = ["Analyze Behavior","Analysis_Design/deliveryprocesses/Analyze Behavior_76D4341A.html"];
contentPage.processPage.elementUrls["_twOBwws0Ee-PSemMSezamg"] = ["Review the Design","Analysis_Design/tasks/review_the_design_61436785.html"];
contentPage.processPage.elementUrls["_HfNFQAsxEe-PSemMSezamg"] = ["Diseño de Guidelines","Analysis_Design/workproducts/Design_guidelines_2FDE899D.html"];
contentPage.processPage.elementUrls["_twPP6As0Ee-PSemMSezamg"] = ["Especificaciones suplementarias","Analysis_Design/workproducts/Supplementary_Specifications_C7445C8B.html"];
contentPage.processPage.elementUrls["_m2RUZgqlEe-zQquRjvk7fw"] = ["Modelo de caso de uso","Analysis_Design/workproducts/Use-Case_Model_1F2B9540.html"];
contentPage.processPage.elementUrls["_2ya3jAszEe-PSemMSezamg"] = ["Event","Analysis_Design/workproducts/Event_1E53D346.html"];
contentPage.processPage.elementUrls["_WJDjMws0Ee-PSemMSezamg"] = ["Identify Design Mechanisms","Analysis_Design/tasks/Identify Design Mechanisms_835256D6.html"];
contentPage.processPage.elementUrls["_WJDjMgs0Ee-PSemMSezamg"] = ["Identify Design Elements","Analysis_Design/tasks/Identify Design Elements_890E5AE0.html"];
contentPage.processPage.elementUrls["_2ya3kAszEe-PSemMSezamg"] = ["Protocol","Analysis_Design/workproducts/Protocol_162F669D.html"];
contentPage.processPage.elementUrls["_WJEKTAs0Ee-PSemMSezamg"] = ["Análisis de clases","Analysis_Design/workproducts/Analysis_Class_840B7D59.html"];
contentPage.processPage.elementUrls["_WJExWAs0Ee-PSemMSezamg"] = ["Signal","Analysis_Design/workproducts/Signal_DAA12F00.html"];
contentPage.processPage.elementUrls["_2yaQdgszEe-PSemMSezamg"] = ["Diseño de Guidelines","Analysis_Design/workproducts/Design_guidelines_2FDE899D.html"];
contentPage.processPage.elementUrls["_Ql_4gQwfEe-e9-FHsoqqEg"] = ["Definir arquitectura candidata","Analysis_Design/deliveryprocesses/Define a Candidate Architecture_3C649D4.html"];
contentPage.processPage.elementUrls["_HfNsVQsxEe-PSemMSezamg"] = ["Realización de casos de uso","Analysis_Design/workproducts/Use-Case_Realization_CCB217D6.html"];
contentPage.processPage.elementUrls["_M3e_YAwfEe-e9-FHsoqqEg"] = ["Analysis Design (process)","Analysis_Design/deliveryprocesses/Analysis Design process_4A71E982.html"];
contentPage.processPage.elementUrls["_XpYtgws0Ee-PSemMSezamg"] = ["Change Request","Analysis_Design/workproducts/change_request_A7B19A71.html"];
contentPage.processPage.elementUrls["_5h6uNAs0Ee-PSemMSezamg"] = ["Event","Analysis_Design/workproducts/Event_1E53D346.html"];
contentPage.processPage.elementUrls["_2ybekAszEe-PSemMSezamg"] = ["Signal","Analysis_Design/workproducts/Signal_DAA12F00.html"];
contentPage.processPage.elementUrls["_WJDjNQs0Ee-PSemMSezamg"] = ["Arquitecto de Software","Analysis_Design/roles/Software Architect_E170FB33.html"];
contentPage.processPage.elementUrls["_5h6HIgs0Ee-PSemMSezamg"] = ["Database Designer","Analysis_Design/roles/Database Designer_87082990.html"];
contentPage.processPage.elementUrls["_HfKB8AsxEe-PSemMSezamg"] = ["Análisis_arquitectónico","Analysis_Design/tasks/Architectural Analysis_BA0A4B6.html"];
